server:
  port: 8080
spring:
  application:
    name: Exam-Gateway
  cloud:
    gateway:
      routes:
        - id: route_member # 登录微服务路由规则
          uri: http://localhost:9000
          predicates: # 断言
            - Path=/login,/admins,/admin/**,/students/**,/student/**,/studentPWD,/teachers/**,/teacher/**

        - id: route_exam # 考试微服务路由规则
          uri: http://localhost:9002
          predicates: # 断言
            - Path=/answers/**,/exams/**,/practices/**,/all/**,/exam/**,/examManagePaperId,/papers,/paper/**,/paperManage,/scores/**,/score/**

        - id: route_question # 题库微服务路由规则
          uri: http://localhost:9002
          predicates: # 断言
            - Path=/fillQuestion,/fillQuestionId,/item,/judgeQuestion,/judgeQuestionId,/multiQuestion,/multiQuestionId

        - id: route_question # 留言微服务路由规则
          uri: http://localhost:9001
          predicates: # 断言
            - Path=/messages/**,/message/**,/replay/**

    nacos:
      config:
        server-addr: 127.0.0.1:8848




